import logging.config
import os

# Define the format of our log messages
# %(asctime)s: Timestamp
# %(levelname)-8s: Log level aligned neatly to 8 characters
# %(name)s: Which file/module generated the log
# %(message)s: The actual text you wrote
LOG_FORMAT = "%(asctime)s | %(levelname)-8s | %(name)s:%(funcName)s:%(lineno)d - %(message)s"

LOGGING_CONFIG = {
    "version": 1,
    "disable_existing_loggers": False, # Don't kill FastAPI's internal logs
    "formatters": {
        "standard": {
            "format": LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler", # Outputs directly to terminal (stdout)
            "formatter": "standard",
            "level": "INFO",
        },
    },
    "loggers": {
        # This catches all logs generated by your custom app code
        "app": { 
            "handlers": ["console"],
            "level": os.getenv("LOG_LEVEL", "INFO"), # Toggled via .env file
            "propagate": False,
        },
        # This intercepts FastAPI/Uvicorn access logs so they match our format
        "uvicorn.access": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

def setup_logging():
    """Call this function once when FastAPI boots up."""
    logging.config.dictConfig(LOGGING_CONFIG)
